baseURL = 'https://www.canoaclubrimini.com'
languageCode = 'it-it'
title = 'Canoa Club Rimini'
theme = "ccr"
relativeURLS = true

[params]
    subtitle = "Scopri insieme a noi il piacere della canoa"

[module]
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"